# Generated by Django 4.0.4 on 2022-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'To do listning holati Yaratildi '), ('done', 'To do listning holati Bajarildi')], default='created', max_length=25, null=True),
        ),
    ]
